<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSjkzxle\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSjkzxle/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSjkzxle.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSjkzxle\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSjkzxle\appDevDebugProjectContainer();
